import type { SidebarsConfig } from '@docusaurus/types';

const sidebars: SidebarsConfig = {
  mainSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'getting-started/quick-start',
        'getting-started/configuration',
        'getting-started/mcp-registration',
      ],
    },
    {
      type: 'category',
      label: 'Claude Skills',
      collapsed: false,
      link: { type: 'doc', id: 'skills/index' },
      items: [
        'skills/index',
        {
          type: 'category',
          label: 'Investigation & Analysis',
          collapsed: false,
          items: [
            'skills/wi-dual-engine',
            'skills/wi-investigate',
            'skills/wi-jira-analyze',
            'skills/wi-investigate-jira-teams-search-ask-topic',
          ],
        },
        {
          type: 'category',
          label: 'Daily Workflow',
          collapsed: false,
          items: [
            'skills/wi-morning-brief',
            'skills/wi-system-memory-workflow',
          ],
        },
        {
          type: 'category',
          label: 'Code, PR & Team',
          collapsed: false,
          items: [
            'skills/wi-code-blast-pr-expert',
          ],
        },
        {
          type: 'category',
          label: 'Maintenance',
          collapsed: false,
          items: [
            'skills/wi-check-links',
            'skills/wi-frontmatter',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Architecture',
      collapsed: false,
      items: [
        'architecture/index',
        'architecture/components',
        'architecture/data-flow',
        'architecture/database-schema',
        'architecture/self-healing-bug-loop',
        'architecture/bug-investigator-agent',
        'architecture/bug-resolver-agent',
        'architecture/review-2026-04-18',
        'architecture/sprint-6-ai-data',
        'architecture/sprint-7-jira-mcp',
        'architecture/embeddings',
        'architecture/mempalace-second-brain',
        'architecture/second-brain-recall',
        'architecture/research-engine',
        'architecture/persona-memory-loop',
        'architecture/wi-router',
        'architecture/unified-buddy-chat',
        'architecture/contract-evolution',
        'architecture/menubar-app',
        'architecture/non-ts-code-graph-coverage',
        'architecture/post-graphify-implementation',
        'architecture/known-gaps',
      ],
    },
    {
      type: 'category',
      label: 'Architecture Decisions (ADRs)',
      collapsed: true,
      items: [
        'adr/adr-001-browser-extraction',
        'adr/adr-002-single-server',
        'adr/adr-003-jira-rest',
        'adr/adr-004-obsidian-smart-clusters',
        'adr/adr-005-teammate-identity-model',
        'adr/adr-006-jira-mcp-fallback',
        'adr/adr-007-mcp-oauth-daemon',
        'adr/adr-008-ep48-implementation-decisions',
        'adr/adr-009-jira-my-work-cockpit',
        'adr/adr-010-meeting-intelligence',
        'adr/adr-011-pr-intelligence-overhaul',
        'adr/adr-012-teams-intelligence-feed',
        'adr/adr-013-intelligent-bug-investigation',
        'adr/adr-014-self-learning-investigation-brain',
        'adr/adr-015-mempalace-integration',
        'adr/adr-016-second-brain-architecture',
        'adr/adr-016-review',
        'adr/ep59-ep60-review',
        'adr/adr-017-always-on-agent-architecture',
        'adr/adr-018-cross-repo-knowledge-sync',
        'adr/adr-019-link-aware-ticket-analysis',
        'adr/adr-020-proactive-intelligence-brain',
        'adr/adr-021-claude-code-research-engine',
        'adr/adr-022-dual-engine-investigation',
        'adr/adr-023-openclaw-plugin',
        'adr/adr-024-unified-brain',
        'adr/adr-025-atlas-operational-surface',
        'adr/adr-026-route-module-extraction',
        'adr/adr-027-code-graph-indexer-scheduling',
        'adr/adr-028-defer-tree-sitter',
        'adr/adr-030-self-healing-bug-loop',
        'adr/adr-031-per-bucket-model-effort-config',
        'adr/adr-032-persona-memory-loop',
        'adr/adr-033-cypher-framework',
        'adr/adr-034-cypher-learning-autonomy-engine',
        'adr/adr-035-chat-brain-unification',
        'adr/adr-036-cypher-cli-primary',
        'adr/adr-037-cypher-tool-use-loop',
        'adr/adr-037-5-cap13-skill-self-extension',
        'adr/adr-038-cypher-v2.5-production-grade',
        'adr/adr-039-cypher-refinement-phase',
        'adr/adr-040-outcome-honest-delivery-kanban',
        'adr/adr-041-ai-optional-enrichment-layer',
        'adr/adr-042-prompt-generation-stage',
        'adr/adr-043-pm-orchestration-layer',
        'adr/adr-044-fetcher-module',
      ],
    },
    {
      type: 'category',
      label: 'Product Requirements (PRDs)',
      collapsed: true,
      items: [
        'prd/cypher-v1.4',
        'prd/cypher-v2.0',
        'prd/cypher-v2.5',
        'prd/code-graph-indexer',
        'prd/fetcher-module',
      ],
    },
    {
      type: 'category',
      label: 'Epics & Backlog',
      collapsed: false,
      link: { type: 'doc', id: 'epics/index' },
      items: [
        { type: 'link', label: '📊 Interactive Dashboard', href: '/backlog-dashboard' },
        'epics/index',
        {
          type: 'category',
          label: '✅ Done',
          collapsed: true,
          items: [
            'epics/ep0-foundation',
            'epics/ep1-browser-session',
            'epics/ep2-teams-scraper',
            'epics/ep3-outlook-scraper',
            'epics/ep4-jira-wiring',
            'epics/ep5-sync-pipeline',
            'epics/ep6-ai-analyzer',
            'epics/ep7-schema-migration',
            'epics/ep10-saturn-jira-report',
            'epics/ep11-teams-sync',
            'epics/ep12-search-all',
            'epics/ep13-topic-expert',
            'epics/ep14-smart-topic-expert',
            'epics/ep15-proactive-agent',
            'epics/ep16-n8n-http-transport',
            'epics/ep17-headless-browser',
            'epics/ep18-error-tracking',
            'epics/ep19-persistent-digests',
            'epics/ep20-saturn-board',
            'epics/ep21-my-jira-issues',
            'epics/ep22-sync-all',
            'epics/ep23-daily-summary',
            'epics/ep24-smart-chat',
            'epics/ep25-calendar-sync',
            'epics/ep26-topic-notebooks',
            'epics/ep28-web-ui-ux-overhaul',
            'epics/ep29-jira-deep-analysis',
            'epics/ep30-teams-updates-redesign',
            'epics/ep31-architecture-hardening',
            'epics/ep32-token-usage-tracking',
            'epics/ep33-data-quality-observability',
            'epics/ep34-relevance-ranked-context',
            'epics/ep35-action-item-triage',
            'epics/ep36-notebook-auto-refresh',
            'epics/ep37-semantic-search',
            'epics/ep38-weekly-pattern-analysis',
            'epics/ep39-cross-topic-relationships',
            'epics/ep40-ai-resilience-model-hygiene',
            'epics/ep41-topic-health-score',
            'epics/ep42-jira-transition-history',
            'epics/ep43-multi-repo-code-intelligence',
            'epics/ep44-pr-intelligence',
            'epics/ep45-teammate-intelligence',
            'epics/ep46-jira-mcp-adapter',
            'epics/ep47-jira-intelligence-layer',
            'epics/ep48-jira-solution-engine',
            'epics/ep49-ux-functional-sprint8',
          ],
        },
        {
          type: 'category',
          label: '✅ Sprint 9 — Done',
          collapsed: true,
          items: [
            'epics/ep50-jira-my-work-cockpit',
          ],
        },
        {
          type: 'category',
          label: '✅ Sprint 10 — Done',
          collapsed: true,
          items: [
            'epics/ep51-pre-meeting-context',
            'epics/ep52-meeting-intelligence',
          ],
        },
        {
          type: 'category',
          label: '✅ Sprint 11 — Done',
          collapsed: true,
          items: [
            'epics/ep53-teams-intelligence',
            'epics/ep54-pr-follow-dashboard',
          ],
        },
        {
          type: 'category',
          label: '✅ Sprint 12 — Done',
          collapsed: true,
          items: [
            'epics/ep55-bug-investigation-engine',
            'epics/ep56-self-learning-brain',
          ],
        },
        {
          type: 'category',
          label: '✅ Sprint 13 — Done',
          collapsed: true,
          items: [
            'epics/ep57-mempalace-integration',
          ],
        },
        {
          type: 'category',
          label: '✅ Sprint 14 — Second Brain: Universal Memory Writer',
          collapsed: true,
          items: [
            'epics/ep58-universal-memory-writer',
          ],
        },
        {
          type: 'category',
          label: '✅ Sprint 15 — Recall-Augmented Chat',
          collapsed: true,
          items: [
            'epics/ep59-recall-augmented-chat',
          ],
        },
        {
          type: 'category',
          label: '✅ Sprint 16 — Autonomous Memory Growth',
          collapsed: true,
          items: [
            'epics/ep60-autonomous-memory-growth',
          ],
        },
        {
          type: 'category',
          label: '✅ Sprint 17 — Always-On Agent Architecture',
          collapsed: true,
          items: [
            'epics/ep61-quick-wins-wave1a',
            'epics/ep62-quick-wins-wave1b',
            'epics/ep63-cdc-pipeline',
            'epics/ep64-orchestrator-agent',
            'epics/ep65-correlation-agent',
          ],
        },
        {
          type: 'category',
          label: '✅ Sprint 18 — Deep Analysis Intelligence',
          collapsed: true,
          items: [
            'epics/ep66-link-aware-ticket-analysis',
            'epics/ep67-claude-code-research-engine',
            // file kept on disk as historical reference (see ADR-023 Superseded).
          ],
        },
        {
          type: 'category',
          label: '📦 Backlog',
          collapsed: true,
          items: [
            'epics/ep8-testing',
            'epics/ep9-cleanup',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Bug Tracker',
      collapsed: false,
      link: { type: 'doc', id: 'bugs/index' },
      items: [
        'bugs/index',
        {
          type: 'category',
          label: '✅ Fixed',
          collapsed: true,
          items: [
            'bugs/bug-01-transaction-dead-abstraction',
            'bugs/bug-02-signal-handler-registration',
            'bugs/bug-03-insert-or-replace-orphans',
            'bugs/bug-04-migrations-not-transactional',
            'bugs/bug-05-wal-mode-not-active',
            'bugs/bug-06-search-uses-like-not-fts5',
            'bugs/bug-07-ghost-topics-unbounded',
            'bugs/bug-08-action-items-duplicated',
            'bugs/bug-09-two-sync-loops',
            'bugs/bug-10-meeting-schema-drift',
            'bugs/bug-12-temperature-extraction',
          ],
        },
        {
          type: 'category',
          label: '📋 Tracked / Documented',
          collapsed: false,
          items: [
            'bugs/bug-11-topic-id-zero-lie',
            'bugs/bug-13-connector-concurrent-navigation',
            'bugs/bug-14-database-path-mismatch',
            'bugs/bug-15-no-prepared-statement-cache',
            'bugs/bug-16-webserver-startup-failures',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Web UI',
      collapsed: false,
      items: ['web-ui/index', 'web-ui/bugs-page'],
    },
    {
      type: 'category',
      label: 'API Reference',
      collapsed: true,
      items: ['api-reference/index', 'api-reference/bugs'],
    },
    {
      type: 'category',
      label: 'Development',
      collapsed: true,
      items: [
        'development/index',
        'development/skill-management',
      ],
    },
    {
      type: 'category',
      label: 'Walkthroughs & Evaluation',
      collapsed: true,
      items: [
        'walkthroughs/loop-trace',
        'evaluation',
      ],
    },
  ],
};

export default sidebars;
